config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: [:new, :create],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  get "", to: 'home#index' 
  
  namespace :panel do
    get "", to: 'dashboard#index'
    resources :users 
    resources :services
    resources :packages do
      resources :package_services, only: [:new, :create, :destroy]
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  role                   :string           default("customer"), not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login

  module Roles
    ADMIN = "admin"
    CUSTOMER = "customer"
  end
  DEFAULT_ROLE = Roles::CUSTOMER
  ROLES = Roles.constants.map {|c| Roles.const_get(c) }

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :role, presence: true, inclusion: { in: ROLES }
  validates_format_of :name, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true, uniqueness: true
  before_validation :set_defaults, on: [:create]

  scope :admins, -> { where(role:Roles::ADMIN)}

  def admin?
    self.role == Roles::ADMIN
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:name) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  private

    def set_defaults
      self.role = DEFAULT_ROLE
    end
end

app/controllers/panel/dashboard_controller.rb
class Panel::DashboardController < PanelController
  load_and_authorize_resource :panel
  def index
  end
end

app/controllers/panel/package_services_controller.rb
class Panel::PackageServicesController < PanelController
  load_and_authorize_resource :package
  load_and_authorize_resource :package_service, through: :package

  # GET /package_services/new
  def new
    # @package_service = @package.package_services.build
  end

  # POST /package_services
  # POST /package_services.json
  def create
    # @package_service = @package.package_services.build(package_service_params)

    respond_to do |format|
      if @package_service.save
        format.html { redirect_to panel_package_path(@package), notice: 'Package service was successfully created.' }
        format.json { render :show, status: :created, location: @package_service }
      else
        format.html { render :new }
        format.json { render json: @package_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /package_services/1
  # DELETE /package_services/1.json
  def destroy
    @package_service.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Package service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #  def set_package
    #   @package = Package.find(params[:package_id])
    # end
    # def set_package_service
    #   @package_service = @package.package_services.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def package_service_params
      params.require(:package_service).permit(:service_id, :service_name)
    end
end

app/controllers/panel/packages_controller.rb
class Panel::PackagesController < PanelController
  load_and_authorize_resource :package

  # GET /packages
  # GET /packages.json
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /packages/1
  # GET /packages/1.json
  def show
  end

  # GET /packages/new
  def new
  end

  # GET /packages/1/edit
  def edit
  end

  # POST /packages
  # POST /packages.json
  def create
    # @package = Package.new(package_params)

    respond_to do |format|
      if @package.save
        format.html { redirect_to panel_package_path(@package), notice: 'Package was successfully created.' }
        format.json { render :show, status: :created, location: @package }
      else
        format.html { render :new }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /packages/1
  # PATCH/PUT /packages/1.json
  def update
    respond_to do |format|
      if @package.update(package_params)
        format.html { redirect_to panel_package_path, notice: 'Package was successfully updated.' }
        format.json { render :show, status: :ok, location: @package }
      else
        format.html { render :edit }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /packages/1
  # DELETE /packages/1.json
  def destroy
    @package.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Package was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_package
    #   @package = Package.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def package_params
      params.require(:package).permit(:name)
    end
end

app/controllers/panel/services_controller.rb
class Panel::ServicesController < PanelController
  load_and_authorize_resource :service

  # GET /services
  # GET /services.json
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    # @service = Service.new(service_params)
    respond_to do |format|
      if @service.save
        format.html { redirect_to panel_service_path(@service), notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to panel_service_path, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_service
    #   @service = Service.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :time, :price)
    end
end

app/controllers/panel/users_controller.rb
class Panel::UsersController < PanelController
  load_and_authorize_resource :user
  #before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to panel_user_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    self_update = true if @user.id == current_user.id
    respond_to do |format|
      if @user.update(user_params_update)
        bypass_sign_in(@user) if self_update
        format.html { redirect_to panel_user_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_user
    #   @user = User.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :role, :password_confirmation)
    end
    def user_params_update
      params[:user].delete(:password) if params[:user][:password].blank?
      params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
      permit_params = [:name, :email, :role]
      if current_user.id == @user.id
        permit_params << :password
        permit_params << :password_confirmation
      end
      # params[:user].delete(:password) if params[:user][:password].blank?
      # params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
      params.require(:user).permit(permit_params)
      # params.require(:user).permit(:name, :email, :password, :role, :password_confirmation)
    end
end

app/controllers/panel_controller.rb
class PanelController < ApplicationController
	before_action :authenticate_user!
  layout "sandstone"
end

app/controllers/users_controller.rb
class UsersController < PanelController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/panel_helper.rb
module PanelHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/panel/users/_form.html.erb
<%= form_for @user, url: panel_user_path(@user) do |f| %>
  Username: <%= f.text_field :name %><br />
  E-mail : <%= f.email_field :email, autofocus: true %><br />
  <%= f.collection_select :role, User::ROLES, :to_s, :humanize %>
  <%= f.submit "Submit"%>
<% end %>

app/views/panel/users/edit.html.erb
<%= form_for @user, url: panel_user_path(@user) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>
  <% if current_user.id == @user.id %>
  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %>
  </div>
  <% end %>

  <% if current_user.admin? %>
    <%= f.collection_select :role, User::ROLES, :to_s, :humanize %>
  <% end %>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<h3>Delete account</h3>

<p>Unhappy? <%= button_to "Delete account", panel_user_path(@user), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>

app/views/panel/users/index.html.erb
<div class="table-responsive">
<table class="table table-bordered">
  <tr>
    <td>Id</td>
    <td>Email</td>
    <td>Data rejestracji</td>
    <td>Rola</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <% @users.order(:id).each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= user.role %></td>
        <td><%= link_to "show", panel_user_path(user.id) %></td>
        <td><%= link_to "edit", edit_panel_user_path(user) %></td>
        <td><%= link_to "delete", panel_user_path(user), remote: false, method: :delete, data: { confirm: 'Are you certain you want to delete this?' }%></td>
      </tr>
  <% end %>
  <tr>
    <td><%= link_to "new user", new_panel_user_path %></td> 
  </tr>
</table>
</div>

app/views/panel/users/new.html.erb
<%= form_for [:panel, @user] do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>
  <%= f.collection_select :role, User::ROLES, :to_s, :humanize %>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>
<% if @user.errors.full_messages.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>

app/views/panel/users/show.html.erb
E-mail: <%= @user.email %><br />
Data rejestracji: <%= @user.created_at %><br/>
Rola: <%= @user.role %>